### ISSUE TITLE
Use cases?

### ISSUE THREAD

**Issue by StephenOTT** [rnschk/camunda-inter-process-token-mover-plugin#1]
What is the use case for this?  Replacing process migration scripts? 

Thoughts on variable movement? 

Thanks

**Comment by rnschk** [comment]
Well, this an ambitious project that comprises a must-have camunda-plugin which enables token-movement in a drag-and-drop manner, even between different processes, engines and even browsers including everything the process-contexts holds mainly variables. Last but not least, as it was released on the 1st of April, it's an April fool, sorry. 🎉 

BG, rnschk

**Comment by StephenOTT** [comment]
Great!  Then you can delete my issue ;)
